config/routes.rb
TodoApp::Application.routes.draw do
  resources :todos

  

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(params[:todo].permit(:title, :description, :completed))
		if @todo.save
			redirect_to @todo
		else
			render 'new'
		end
	end

	def show
		@todo = Todo.find(params[:id])
	end

	private 
		def todo_params
			params.require(:todo).permit(:title, :desctiption, :completed)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>Tony's Todos</h1>

<table>
		<tr>
			<th>Title</th>
			<th>Description</th>
			<th>Completed?</th>
		</tr>
	<% @todos.each do |todo| %>
		<tr>
			<td><%= todo.title %></td>
			<td><%= todo.description %></td>
			<td><%= todo.completed %></td>
		</tr>
	<% end %>
</table>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<table>
	<%= form_for @todo do |t| %>

			<tr>
				<td><%= t.label :title %></td>
				<td><%= t.text_field :title %></td>
			</tr>

			<tr>
				<td><%= t.label :description %></td>
				<td><%= t.text_area :description %></td>
			</tr>

			<tr>
				<td><%= t.label :completed %></td>
				<td>
					<%= t.select(:completed, options_for_select([['Yes', true], ['No', false]], false)) %>

				</td>

			</tr>
		<%= t.submit %>
	<% end %>
</table>

app/views/todos/show.html.erb
<h1>Todo <%= @todo.id %></h1>

<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
	</tr>
	<tr>
		<td><%= @todo.title %></td>
		<td><%= @todo.description %></td>
	</tr>
</table>
<br>

<%= link_to 'Back to Index', todos_path %>